### ISSUE TITLE
Error in Tab Pivot 

### ISSUE THREAD

**Issue by Matteo12345889** [radiant-rstats/radiant#194] opened 2023-01-05 10:31 UTC
In the tab Pivot, when I click "Show plot" after making a table of two categorical variables, it doesn't work, it shows me the following message instead of the plot: 

Error: 'what' must be a function or character string

This started to happen after I left my PC for a while and I found it in stand-by. Then I closed Radiant, re-opened it and then the problem started to appear.

help me pls. Thanks

**Comment by vnijs** [comment] 2023-01-06 06:53
I can't reproduce the issue you are seeing (see screenshot below). Please run the commands below to get the latest versions of all radiant packages. 

```
options(repos = c(RSM = "https://radiant-rstats.github.io/minicran", CRAN = "https://cloud.r-project.org"))
install.packages("remotes")
remotes::install_github("radiant-rstats/radiant.update", upgrade = "never")
radiant.update::radiant.update()
```

![image](https://user-images.githubusercontent.com/2998956/210946601-4dc6a3f1-6657-4f90-b3e8-fb8d74834dfa.png)

**Comment by vnijs** [comment] 2023-01-13 23:06
Closing for now. Reopen if needed.

**Closed as completed by vnijs** 2023-01-13 23:06 UTC
