### ISSUE TITLE
Connecting to OLAP Cubes

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#55] opened 2018-05-02 22:56 UTC
Is there an easy way to connect to OLAP Cubes in Radiant?

**Comment by vnijs** [comment] 2018-05-02 23:08
I have not used OLAP cubes before. Can you provide an example of how you would access one from R?

You could certainly do the following in _Report > R_ (or _Report > Rmd_).

```r
## insert code to access OLAP cube
my_dataset <- ...
register("mydataset")
```

The data.frame will then be available from the dropdown menus and can be used in with any of the analysis and visualization tools. You can filter the data further in _Data > View_ and if you need a new query tweak your code in _Report > R_ to update the data.frame

Would something like that work for you?

**Comment by josh1400** [comment] 2018-06-07 03:15
I have not connected to an OLAP cube in  R so I'm not sure how it would be done.
**However, I'm having issues running the following code in Radiant:**
```{r}
library(RODBC)
```
```{r}
Master.Data <- odbcDriverConnect('driver={SQL Server};server=EXAMPLE\\EXAMPLE;database=Example;trusted_connection=true')
register(Master.Data)
```
```{r}
CSP <- sqlFetch(Master.Data, "iwpl.v_csp")
register(CSP)
```
```{r}
## Load commands
CSP <- get("CSP", envir = .GlobalEnv)
register("CSP")
```

**I can run the following in Rstudio:**

library(RODBC)
Master.Data <- odbcDriverConnect('driver={SQL Server};server=EXAMPLE\\EXAMPLE;database=Example;trusted_connection=true')
CSP <- sqlFetch(Master.Data, "iwpl.v_csp")

**Then run the following in Radiant:**
```{r}
## Load commands
CSP <- get("CSP", envir = .GlobalEnv)
register("CSP")
```

**Comment by josh1400** [comment] 2018-06-07 03:16
I imagine that connecting to an OLAP cube would be similar.  So I'd be happy to know how to make this work.

**Comment by vnijs** [comment] 2018-06-07 03:47
I see a couple of issues in the code. First, only data frames can be registered, not database connections. I'm not sure if CSP is a data frame or if it needs to be "collected" first. If it is a data frame, use register("CSP"). Note the quotes. If CSP is a data frame, the code below should work. There is no need to use `get` here because when you create CSP in _Report > Rmd_ or _Report > R_ it is automatically included in the correct environment in Radiant.

```r
Master.Data <- odbcDriverConnect('driver={SQL Server};server=EXAMPLE\\EXAMPLE;database=Example;trusted_connection=true')

CSP <- sqlFetch(Master.Data, "iwpl.v_csp")
register("CSP")
```

**Comment by josh1400** [comment] 2018-06-07 04:28
I usually connect to Master.Data then load CSP into my global environment with the sqlFetch code.

Then I open Radiant and can load CSP from the global workspace using get()

Is that as automated as I can get?

**Comment by vnijs** [comment] 2018-06-07 04:37
You can do it that way. However, I'd put the code directly in _Report > Rmd_ so that if you share the state file with some one else they can reproduce your results exactly from start to finish.

**Comment by josh1400** [comment] 2018-06-07 04:53
That's what I want to do, but putting the following into _Report > Rmd_ didn't work.

```{r}
library(RODBC)
Master.Data <- odbcDriverConnect('driver={SQL Server};server=EXAMPLE\\EXAMPLE;database=Example;trusted_connection=true')
register(Master.Data)
CSP <- sqlFetch(Master.Data, "iwpl.v_csp")
register(CSP)
```

What is the problem?

**Comment by vnijs** [comment] 2018-06-07 05:08
Check my previous reply on GitHub

**Comment by vnijs** [comment] 2018-06-07 06:03
You are missing the quotes around the data frame name

**Comment by josh1400** [comment] 2018-06-07 16:54
Thank you.  That worked

**Comment by vnijs** [comment] 2018-06-07 22:12
I'll close this for now. Reopen if needed

**Closed as completed by vnijs** 2018-06-07 22:12 UTC

**Comment by josh1400** [comment] 2018-06-15 18:32
How would connecting to a multidimensional cube database affect how Radiant interacts with the data?

https://docs.microsoft.com/en-us/sql/advanced-analytics/r/using-data-from-olap-cubes-in-r?view=sql-server-2017
