### ISSUE TITLE
correlation analysis

### ISSUE THREAD

**Issue by ghost** [radiant-rstats/radiant#10] opened 2016-11-03 16:19 UTC
Hi!
When a perform correlation analysis, changing the value of dropdown menu with methods (pearson,spearman, kendall) doesnt changing values in the analysis tab.

**Comment by vnijs** [comment] 2016-11-03 16:59
Thanks for reporting that @Fiordmaster. Should be fixed now. If you run `radiant::update_radiant()` or choose `Update Radiant` from the Rstudio Addins menu you should get the latest version that works as intended.

**Closed as completed by vnijs** 2016-11-03 16:59 UTC
