### ISSUE TITLE
Issues with installation / loading data

### ISSUE THREAD

**Issue by rsuhada** [radiant-rstats/radiant#140] opened 2020-10-04 18:10 UTC
Dear Vincent,

when trying the recommended install:

    install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/")

I get an error:

    package 'radiant' is not available (for R version 3.6.3) 

(this is indeed the correct version of my R).

If I instead do just `install.packages("radiant")`, radiant is installed without issues.
However running it with `radiant::radiant()` gives me only the top menu bar (grayed out), and clicking on data doesn't do anything (same for help etc.)

![image](https://user-images.githubusercontent.com/818539/95023455-616acd00-067d-11eb-8bd6-59d15747ef75.png)

The console has a an error:

      /home/rxs/R/x86_64-pc-linux-gnu-library/3.6/radiant.design/app/tools/analysis/sample_size_ui.R:27:26: unexpected INCOMPLETE_STRING
    26:         condition = "input.ss_type == 'mean'",
    27:         tags$div(title = "The acceptable error is the level of precision you require (i.e., the range within which the true mean should lie). For example, 

Thank you!

**Comment by vnijs** [comment] 2020-10-06 08:15
I don't have access to R 3.6 on linux so this may be hard to replicate. That said, this might be caused by the fact that the psych package depends on at least on package that requires R 4.0 ... which would then basically mean that Radiant now requires R 4.0. Can you upgrade?

**Comment by vnijs** [comment] 2021-04-28 00:25
Closing ...

**Closed as completed by vnijs** 2021-04-28 00:25 UTC
