### ISSUE TITLE
Decision Tree Chart

### ISSUE THREAD

**Issue by jab57** [radiant-rstats/radiant#69] opened 2018-07-30 19:18 UTC
Chart extremely small when I generate the tree chart for regression tree.  The tree is computed correctly but the display is extremely small.

**Comment by jab57** [comment] 2018-07-30 19:27
It is generating a very large tree with a large number of nodes but the chart is not displaying correctly on the screen.

**Comment by jab57** [comment] 2018-07-30 19:31
[~$Doc2.docx](https://github.com/radiant-rstats/radiant/files/2242607/Doc2.docx)


Let me know if you can see this doc.

**Comment by vnijs** [comment] 2018-07-30 19:42
That helps. 

(1) The more nodes the smaller each node unless you, either, "zoom" in your browser or reduce the number of nodes
(2) Increase the "Width" to a larger number (set to 1400 in the screen shot I posted previously)
(3) I can't open the Word file. However, there is an issue in webshot (as far as I can tell) that produces these very small images to embed in Word or PDF. See the issue linked below. This does work fine on macOS but not on Windows. I recommend you use HTML or Notebook as the output format in _Report > Rmd_ instead

https://github.com/wch/webshot/issues/41

**Comment by jab57** [comment] 2018-07-30 19:45
![capture](https://user-images.githubusercontent.com/41925323/43419647-109bb1c0-9431-11e8-831a-64eed2f1a366.PNG)

**Comment by vnijs** [comment] 2018-07-30 20:00
I see. I cannot reproduce this on macOS, Windows, or Linux using the Chrome browser. Please upgrade to the latest version of radiant using the commands below. If the issue still exists, please post the output from `sessionInfo()`. 

It looks like the tree is not fully rendering either (i.e., no labels). What browser are you using? Hopefully not Internet Explorer or Edge :)

```
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
```

**Comment by jab57** [comment] 2018-07-30 20:01
![capture1](https://user-images.githubusercontent.com/41925323/43420437-3095b0c8-9433-11e8-9eb4-9e8263d3df60.PNG)
![capture](https://user-images.githubusercontent.com/41925323/43420440-33110370-9433-11e8-9fc3-eaa9e93e8c97.PNG)


here is the tree and the chart.  I am using IE.

**Comment by vnijs** [comment] 2018-07-30 20:06
I think the issue is most likely the browser then. IE doesn't adhere to modern web-browser standards I'm afraid and the libraries that radiant builds on are not well supported by IE. Microsoft Edge might work but I'd highly recommend Chrome.

**Comment by jab57** [comment] 2018-07-30 20:07
Would Mozilla Firefox work?

**Comment by vnijs** [comment] 2018-07-30 20:09
Firefox should work fine as well. Radiant will always start in your default browser. You can copy-and-paste the URL from IE into Firefox to try it out but if you use radiant a lot I would recommend switching to firefox or chrome full time.

**Comment by jab57** [comment] 2018-07-30 20:10
Thanks!

**Comment by vnijs** [comment] 2018-08-01 05:35
I'll close this issue for now. Reopen if needed.

**Closed as completed by vnijs** 2018-08-01 05:35 UTC

**Comment by jab57** [comment] 2018-08-03 01:12
Thank you very much. Appreciate your help.
