### ISSUE TITLE
register() not saving the datasets for use in Radiant

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#58] opened 2018-06-01 17:14 UTC
I have a report where datasets are created, adjusted, registered, then used in other datasets.  When I knit my report, it all works.  This means the data is being registered somewhere since it's changed, saved, and used multiple places in the report.

However, my list of datasets in the data tab only has the original data.  All my created datasets are no where to be found.  I can see them in the preview section of the report so I know they are somewhere.

This just started happening when the update removed the store function.  When I tried to add it back in, there are errors.

**Comment by vnijs** [comment] 2018-06-01 17:56
Can you check that you are running the latest version of `radiant.data`? Should be 0.9.4.6. Use:

`packageVersion('radiant.data')`

To update to the latest version, which requires R 3.4 or 3.5, use the commands below:

```
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
```

If you still have issues, please provide sessionInfo using the command below:

```
sessionInfo()
```

**Comment by josh1400** [comment] 2018-06-01 18:31
> packageVersion('radiant.data')
[1] ‘0.9.4.6’
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] bindrcpp_0.2.2               shiny_1.1.0                  radiant_0.9.4.0              radiant.multivariate_0.9.4.1 radiant.model_0.9.4.1        radiant.basics_0.9.4.0      
 [7] radiant.design_0.9.4.0       mvtnorm_1.0-7                radiant.data_0.9.4.6         dplyr_0.7.5                  tidyr_0.8.1                  lubridate_1.7.4             
[13] ggplot2_2.2.1                magrittr_1.5                 RODBC_1.3-15                

loaded via a namespace (and not attached):
  [1] colorspace_1.3-2      class_7.3-14          rio_0.5.10            rprojroot_1.3-2       markdown_0.8          base64enc_0.1-3       rstudioapi_0.7.0-9001 DT_0.4               
  [9] ggrepel_0.8.0         RSpectra_0.12-0       Gmedian_1.2.4         mnormt_1.5-5          robustbase_0.93-0     knitr_1.20            jsonlite_1.5          broom_0.4.4          
 [17] data.tree_0.7.5       DiagrammeR_1.0.0      readr_1.1.1           compiler_3.4.2        httr_1.3.1            backports_1.1.2       assertthat_0.2.0      Matrix_1.2-14        
 [25] lazyeval_0.2.1        later_0.7.2           visNetwork_2.0.3      htmltools_0.3.6       tools_3.4.2           igraph_1.2.1          gtable_0.2.0          glue_1.2.0           
 [33] reshape2_1.4.3        Rcpp_0.12.17          carData_3.0-1         cellranger_1.1.0      rgexf_0.15.3          nlme_3.1-137          crosstalk_1.0.0       psych_1.8.4          
 [41] stringr_1.3.1         openxlsx_4.0.17       mime_0.5              XML_3.98-1.11         shinyAce_0.3.1        DEoptimR_1.0-8        MASS_7.3-50           zoo_1.8-1            
 [49] scales_0.5.0          hms_0.4.2             promises_1.0.1        parallel_3.4.2        sandwich_2.4-0        RColorBrewer_1.1-2    yaml_2.1.19           curl_3.2             
 [57] gridExtra_2.3         downloader_0.4        rpart_4.1-13          stringi_1.1.7         highr_0.6             AlgDesign_1.1-7.3     Rook_1.1-1            e1071_1.6-8          
 [65] polycor_0.7-9         rlang_0.2.0           pkgconfig_2.0.1       evaluate_0.10.1       lattice_0.20-35       purrr_0.2.4           bindr_0.1.1           labeling_0.3         
 [73] NeuralNetTools_1.5.1  htmlwidgets_1.2       import_1.1.0          tidyselect_0.2.4      plyr_1.8.4            R6_2.2.2              pillar_1.2.2          haven_1.1.1          
 [81] foreign_0.8-70        abind_1.4-5           nnet_7.3-12           tibble_1.4.2          crayon_1.3.4          car_3.0-0             plotly_4.7.1          rmarkdown_1.9        
 [89] viridis_0.5.1         grid_3.4.2            readxl_1.1.0          data.table_1.11.2     influenceR_0.1.0      forcats_0.3.0         digest_0.6.15         xtable_1.8-2         
 [97] httpuv_1.4.3          GPArotation_2014.11-1 brew_1.0-6            munsell_0.4.3         viridisLite_0.3.0

**Comment by vnijs** [comment] 2018-06-01 18:38
Any chance you can email me the state file or share through Dropbox? Actually, have you tried saving the state file and then loading it back in?

**Comment by josh1400** [comment] 2018-06-01 18:54
That seems to have fixed the issue.

**Comment by vnijs** [comment] 2018-06-01 19:39
There have been some pretty big structural changes in how Radiant works with data. See link below. When you run _Report > Rmd_ or _Report > R_ most required updates should be handled automatically. If you find a (reproducible) problem please do report in detail and I will try to help you fix the issue

https://radiant-rstats.github.io/docs/news.html

I'll close this issue for now but feel free to re-open as needed

**Comment by vnijs** [comment] 2018-06-03 03:20
In case @josh1400 is the Josh I know and whose email recently seems to have stopped working ...

I have been working to try to make R, Rstudio, and Radiant more easily accessible and reproducible. To that end I created a set of Docker containers. Thought you might find this interesting. See the repo linked below. The radiant image is probably what you want but in case you are also interested in python and jupyter see the rsm-msba image
 
https://github.com/radiant-rstats/docker

**Comment by josh1400** [comment] 2018-06-05 19:04
The issue seems to be persisting when I leave Radiant open for long period of time.  Restarting Rstudio always seems to fix the issue. When the issue is happening, I can quit Radiant, clear my global environment, reload my initial datasets, load the state file that has no saved datasets (just the code), load the initial data from the global workspace, then knit the report.  When I do this, the report shows all the new datasets and I can use them by running code in the report, but it's not in the Radiant GUI for further use.  When I look at the Rstudio console, I see the following output.

> radiant:::radiant()

Starting radiant in the default browser ...

Use radiant::radiant_viewer() in Rstudio to open radiant in the Rstudio viewer or radiant::radiant_window() in Rstudio to open radiant in an Rstudio window

Listening on http://127.0.0.1:4331
No dataset with that name has been loaded in Radiant
No dataset with that name has been loaded in Radiant
No dataset with that name has been loaded in Radiant
Warning: Column `mpn` joining factors with different levels, coercing to character vector
Warning: Column `design_id` joining factors with different levels, coercing to character vector
No dataset with that name has been loaded in Radiant
No dataset with that name has been loaded in Radiant
Warning: Column `mpn` joining character vector and factor, coercing into character vector
No dataset with that name has been loaded in Radiant
No dataset with that name has been loaded in Radiant

**Comment by vnijs** [comment] 2018-06-05 19:12
Can you email me the state file so I can take a closer look?

**Comment by vnijs** [comment] 2018-06-06 19:22
Looking at the messages you posted I don't think you actually loaded the data from the global environment into Radiant. To make data accessible to drop downs etc. it needs to be in the `r_data` environment. You do that through the _Data > Manage_ tab or using the command below. If you don't take that step Radiant can still access the data from the Global Environment in _Report > Rmd_ and _Report > R_ but `register` won't work because the data is not in Radiant's environment. Please double check and let me know.

Question: Why don't you load the data you want directly into Radiant through _Report > Rmd_?

```{r}
## Load commands
dat <- get("dat", envir = .GlobalEnv)
register("dat")
```

![image](https://user-images.githubusercontent.com/2998956/41060009-1ff8fd22-6983-11e8-8138-0c6497269631.png)

**Comment by josh1400** [comment] 2018-06-06 23:56
That's not the case.  I have those commands as part of my report.  The three datasets that I load from my global environment are usable in the GUI.  The datasets that aren't saved are the ones that are built from my initial datasets.  For example, I load "A" from my global environment.  I filter "A" and register it as "A_wrk".  I then load "B" from my global environment.  I filter "B" and register it as "B_wrk".  I then combine "A_wrk" and "B_wrk" and register it as "AB".

In the report, I can view "AB", I can visualize "AB", etc. by adding code.  However, in Radiant, I still only see "A" and "B".  I don't see "A_wrk", "B_wrk", or "AB".

This problem is fixed when I restart Rstudio and only occurs when I've left Radiant open for a while so it's not really a burden.  However, it's happened multiple times since the update so there seems to be something wrong.

**Comment by vnijs** [comment] 2018-06-07 00:01
Strange. This should definitely not happen. I'd very much like to look into this more. Can you share the state file or else (parts of) the code so I can try to re-create and test?

**Comment by josh1400** [comment] 2018-06-07 03:05
The data is sensitive so I can't share the state.  I could share the code, but I'd be surprised if that was the problem.  The code works seamlessly 99% of the time.  When the problem occurs, restarting Rstudio fixes it.

**Comment by vnijs** [comment] 2018-06-07 03:52
I haven't been able to reproduce the issue based on the description you provided. There are 3 possible causes: 1. an issue in your code, 2. an issue in radiant, or 3. an issue in Rstudio's shiny package. If you can email me the code, I should be able to rule out option 1 and create a reproducible example to determine if this is option 2 or 3. I hope you will be able to help me out because this could be an important problem to get fixed

**Comment by vnijs** [comment] 2018-06-14 15:52
New version posted (radiant.data 0.9.5.1). The update should close the issue. Please update and confirm. Thanks for reporting this issue @josh1400!

**Comment by vnijs** [comment] 2018-06-15 18:47
@josh1400 Were you able to verify that the `register` issue you were having no longer occurs after the update?

**Comment by josh1400** [comment] 2018-06-15 19:42
The issue hasn't reoccurred.

**Comment by vnijs** [comment] 2018-06-15 19:50
Thanks Josh. See https://github.com/radiant-rstats/radiant.data/blob/master/NEWS.md

**Closed as completed by vnijs** 2018-06-15 19:50 UTC
