### ISSUE TITLE
Cannot save .csv, rda, rds

### ISSUE THREAD

**Issue by BadgerDaniel** [radiant-rstats/radiant#148] opened 2021-02-15 17:42 UTC
Attempting to save data in any format other than radiantstate is impossible. 
It shows the saving/loading bar briefly before making the screen covered in a grey tint, and the file is not downloaded or saved.

**Comment by BadgerDaniel** [comment] 2021-02-16 16:10
before running radiant

install.packages("readr")

**Comment by vnijs** [comment] 2021-02-18 08:05
I cannot reproduce. Are there any messages shown in Rstudio or is this on a server? The more detail you can provide the better.

**Comment by vnijs** [comment] 2021-02-20 19:41
@BadgerDaniel Can you provide more information so I can try to reproduce the issue you are seeing?

**Comment by vnijs** [comment] 2021-04-08 02:37
Closing for now. I can't replicate and there was no follow up from OP

**Closed as completed by vnijs** 2021-04-08 02:37 UTC
